### ISSUE TITLE
When i run the example“find_facial_features_in_picture.py  ” code error

### ISSUE THREAD

**Issue by cuimiao187561** [ageitgey/face_recognition#10]
* face_recognition version:‘’0.1.0‘’
* Python version:2.7.6
* Operating System:ubantu

 Description error：
gnss523@gnss523:~/Desktop/face_recognition-master/examples$ python     find_facial_features_in_picture.py    
	
Traceback (most recent call last):
	File "find_facial_features_in_picture.py", line 5, in <module>
    image = face_recognition.load_image_file("biden.jpg")
	File "/usr/local/lib/python2.7/dist-packages/face_recognition/api.py", line 62, in load_image_file
    return scipy.misc.imread(filename, mode=mode)
	TypeError: imread() got an unexpected keyword argument 'mode'
please  tell  my
thank you

**Comment by ageitgey** [comment]
This is the same problem reported in #6. This issue happens if you have too old a version of `scipy`. Can you try the solution [listed here](https://github.com/ageitgey/face_recognition/issues/6#issuecomment-287122632)?

```
pip install --upgrade scipy
```

Alternately, you could try reinstalling this library because the latest version should hopefully force a newer version of scipy to be installed:

```
pip install --reinstall face_recognition
```

Let me know if that fixes it.
