### ISSUE TITLE
face verification

### ISSUE THREAD

**Issue by flyingmrwang** [ageitgey/face_recognition#1022]
* face_recognition version: 1.2.3
* Python version:3.6
* Operating System: centos7

### Description
This work is very helpful to check if two images come from the same person. But my case is I have a pool of faces of same person. How can I improve the accuracy by comparing my probe image with the pool rather than random chosen one? Can I get one embedding with a pool of same person face images?

**Comment by alessiosavi** [comment]
This packages is a wrapper for the `dlib` library. It use some mathematical method in order to compare the result of the `face_embedding` (the vector that contains the point of the face) such as euclideian distance. What you are trying to do, is something that is solved by a neural network. You need to collect some faces for the target person, let the neural network "study" the face points extracted. You can rely on my little tool `PyRecognizer`. It use `face_recognition` package in order to extract the points related to the face, than feed a neural network in order to "save" the data of the person. After the train/tune process, you can predict a new photos of the same people(s) that the network was trained against. The tool rely on a MLP network. You can find more information (such as train with your dataset or use the predict method) in the repository pages.  https://github.com/alessiosavi/PyRecognizer

**Comment by flyingmrwang** [comment]
> This packages is a wrapper for the `dlib` library. It use some mathematical method in order to compare the result of the `face_embedding` (the vector that contains the point of the face) such as euclideian distance. What you are trying to do, is something that is solved by a neural network. You need to collect some faces for the target person, let the neural network "study" the face points extracted and then predict the faces accordlying to a threshold. You can rely on my little tool `PyRecognizer`. It use `face_recognition` package in order to extract the points related to the face, than feed a neural network in order to "save" the data of the person. After the train/tune process, you can predict a new photos of the same people(s) that the network was trained against. The tool rely on a MLP network. You can find more information (such as train with your dataset or use the predict method) in the repository pages. https://github.com/alessiosavi/PyRecognizer

Thanks for your hint. From my current understanding, your work is to extract pattern of target face with input of batch of key points and with the tool of MLP. But what I am wondering is if there is a way to merge the face_embeddings of a batch of target face. Cuz in this way, the merging part can be done offline, and the verification part could be very light weight and fast.

**Comment by alessiosavi** [comment]
> From my current understanding, your work is to extract pattern of target face with input of batch of key points and with the tool of MLP.
You are quite right. `PyRecognizer`  use the `face_recognition` package in order to extract the faces encodings. Instead of save this array, i extract all the encodings related to a particular person in batch, something like this:
```python
encodings = []
for photo in folder_person:
    encodings.append(extract_face_point(photo)
```

Now that i have an array with the different encodings of the same person, i train a neural network (MLP in my case) in order to "understand how is" the face of the target person. By this way, you haven't to save the encodings related to the person in order to iterate among the different encodings each time you need to recognize the person, cause they are saved in the NN internally. The `prediction phase` is instant.

**Comment by flyingmrwang** [comment]
@alessiosavi So, you are merging the encodings with MLP. This is how most face recognition NNs work, right? But the problem of this topology is we cannot verify the unseen face. I believe that your work can have a great accuracy for test set. But my challenge is I not only have so many ids, but also an increasing number of ids, which means my model should work good for ids which are out size of training set. Correct me if I am wrong :)

**Comment by alessiosavi** [comment]
> So, you are merging the encodings with MLP. 

Quite right, the MLP is able to "understand" (=math magic on arrays) the encoding related to the people, but it does not applicate any merge between data.

> But the problem of this topology is we cannot verify the unseen face. I believe that your work can have a great accuracy for test set.

Have a try, it's tuned among some celebrities. Try to download a photo related to a person that have few photo (you can see the list on the Readme of the project) and use the `threshold` parameter to verify how much is accurate. Some celebs have only 6-10 photos.
He perform very well with multi faces and with never seen photos. 

I think that we can move the issue on the project, cause your questions start to be not related to the `face_recognition` tool (:

**Comment by flyingmrwang** [comment]
@alessiosavi Ok, I will have a try of your tool in these days. Thanks for your kind explanations!

**Comment by alessiosavi** [comment]
It's a pleasure. Do not hesitate to open issue in order to ask how the tool work internally. Cheers (:

**Comment by yurygodyna** [comment]
Посмотри, это может быть полезно нам


С уважением,
Годына Юрий

От: i.gusev@smevents.org
Отправл.: 5 марта 2020 г. 13:23
Кому: sales@facemetric.ru
Тема: Российский межотраслевой Форум «Завод 4.0: Цифровая трансформация промышленности»


Добрый день.

В продолжение диалога с Юрием направляю информацию о Российском межотраслевом Форуме «Завод 4.0: Цифровая трансформация промышленности».

Сейчас на основании запросов потенциальных участников идет отбор организаций, которые обладают решениями по части компьютерного зрения.

Среди компаний находящихся на рассмотрении:
- Центр 2М;
- Визиллект;
- BAUM и другие.

Рассмотрите возможность участия в качестве спикера Круглого стола.


Подробная информация во вложении.

Официальный сайт мероприятия: http://smevents.org<http://smevents.org/zavod-4/>

Организатор: <http://www.ensoenergy.org/> ООО «<http://www.ensoenergy.org/>SM Events»<http://smevents.org/>

Дата проведения: 11 сентября 2020 г.

Место проведения: г. Москва, Марриотт Отель Новый Арбат

Вложения:
1. Брошюра Форума
2. Проект деловой программы
3. Список запланированных участников

--

С уважением,

Илья Гусев

Руководитель отдела продаж


SM Events<http://smevents.org/>

Tel.: +7 (351) 239-12-99

Mobile: +7 (968) 126-34-26

Офис: Челябинск

**Comment by yurygodyna** [comment]
Привет!

Пришли Жене актуальную презентацию для банков


С уважением,
Годына Юрий

От: egusev@intact.ru
Отправл.: 24 марта 2020 г. 8:31
Кому: ygodyna@facemetric.ru
Тема: Презентация Facemetric Для банков


Юр, привет!

Есть что то подобное?


С уважением,
Евгений Гусев

+7 (495) 989 40 49 доб. 2009
+7 (977) 291 32 31

**Comment by yurygodyna** [comment]
С уважением,
Годына Юрий

От: MStyugin@sk.ru
Отправл.: 27 апреля 2020 г. 17:28
Кому: ygodyna@facemetric.ru
Тема: конкурс по безопасности Сколково


Добрый день!
Встретил вашу презентацию среди заявок на выставку SUV.
Предлагаю также рассмотреть возможность подачи на конкурс https://cyberday.sk.ru/cybersecurity-challenge/


--
С уважением, Михаил Стюгин
Руководитель направления «Информационная безопасность»
Кластер информационных технологий | Фонд «Сколково»
Раб.: +7 (495) 956-00-33 доб. 3587 | Моб.: +7 (977) 977-15-19
Е-mail: MStyugin@sk.ru<mailto:MStyugin@sk.ru>

**Comment by yurygodyna** [comment]
С уважением,
Годына Юрий

От: darina@axisinnovation.com
Отправл.: 17 мая 2020 г. 17:48
Кому: ygodyna@facemetric.ru
Кому: darina@axisinnovation.com
Тема: Samsung, Kaspersky, and Liberty Global - Yuri, Don't miss the Axis Webinar!




        View in browser<https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2MzAmZD1uNXI1dDRo.LxrEpqr4uJnLXxVJedbO2LOU_9ptcAfPYOqD4zXLIVQ>



[https://bucket.mlcdn.com/a/199/199499/images/7c7f352d2b22eebe3563c7a5f8a25d391d7a359d.png/27520828ae956a2e1262dc4338d2b2cd99d63e10.png] <https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2MzYmZD1yN2Q4dzF1.J_CGFeptIGfkoiICcmMDm-2Y58aQxgRwMuOMpM0WqzQ>





Hi Yuri,

Do you want to learn from global corporations - how do startups fit into the bigger picture of innovation?

If you're a startup, investor, or anyone from the ecosystem - don't miss the chance to hear the inside story of how corporate innovation really works!

Join Axis Webinar tomorrow at 3pm CET (4pm Israel Time). Click here<https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2NDAmZD1lOWc0aTZx.fFXiqnV4DkTi5DRuuavPTDuH3b8IkA3ppi-tz5NFqP4> to add a reminder to your Google calendar.






Register<https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2NDgmZD1pMnI4bjN1.1XRc6GCHUhrCFBA8ncN1k1_CDUkqRstI3Y9jX8x83Ho>







Proudly sponsored by DLA PIPER<https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2NTImZD1rMXo3dTdl.4e_3z89rd2JcVXsdl81VYLHs2zXxSGuhN2OKsq3hZNM>







Meet our Speakers
More<https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2NjAmZD1hMmo1YTdp.ryPAh8BXbsOlxgH7_Dk57hfyIdfnt08PgSZPe8SSSog>



[https://bucket.mlcdn.com/a/199/199499/images/b33c415805c9b1740e128f26dc78d50760cc2475.jpeg/9f26a2be4feeb29c168b248eb45943cc12351086.jpeg]<https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2NjImZD1iN2o3ZTFv.8jleTv_e35RbNAabJ9NS7U_YKUm058bK235ZgmCwQJM>

Lior Yekoutieli


Head of Open Innovation Group @ Samsung Research (Israel)



[https://bucket.mlcdn.com/a/199/199499/images/73b6f2b7191e8bddfea752d20212d7a112df9dcd.jpeg/19cc93a7d2112b4fa138c09b5b01ee9e00f65552.jpeg]<https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2NjQmZD1xMWI1YjBz.4KlRzQmAdrKrCs3Sy1LSZ3Czdd_PIZ0Azyvic0x5Xa0>

Andrey Nikonov


Corporate Startup Engagement Lead @ Kaspersky Innovation Hub (Russia)


[https://bucket.mlcdn.com/a/199/199499/images/3205afd793ded0b815dbb5ddb87e84db240e7cf8.jpeg/a924eea0c6a61e82fcfabab3134bfbb71fc31411.jpeg]<https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2NjYmZD15NG00czFv.nisNOIlwIzyH2_VqKjGjVkHDPz3B1guTP1DZTTIo5ZA>

Bruce Dines


Partner @ Liberty Global Ventures (USA)









[https://bucket.mlcdn.com/a/199/199499/images/727ca753bcef97ba1ce93a5fb584af6df92e5d71.jpeg/85a091bb57c9ac57420af9a6bf5505a73c00f8ee.jpeg]<https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2NjgmZD1rMncyeTJp.xTkLxmfg_WjE7Jiq_zNYkQvzuLde_JKUGeRox1vcQhQ>

Naomi Maryles


Inroduction by Director of Israel BD @DLA Piper (Israel)



[https://bucket.mlcdn.com/a/199/199499/images/89c712bbea6f405552137da3b2a96addce8cce08.jpeg/1a81915ad4a6dbbb700cc2a1dd69258d800a1549.jpeg]<https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2NzAmZD1sNHo1ZDlj.tzvQphjy_n8haS96l_X6sfr5NCIgoNr8h7ZyBUWHKZI>

Jason Weiss


Moderator, COO @Axis Innovation (Israel)







Register<https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2NzQmZD1sMm8wdThs._I9_pCFzUMFnIO2C8qWwXp0uJ7Z1Ch6jS7mvDwqdLrM>







Some of the most important questions we will discuss:

- When is it the right time for a corporation to work with external partners and startups?

- How have corporate innovation strategies changed since the Corona Virus?

- Are companies more or less open to working with external partners?

- Your questions!






[https://bucket.mlcdn.com/a/199/199499/images/b5cd29fd891338004cbf82f741cb0becc8b56318.jpeg] <https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2NzYmZD1tM3k5cDht.fxJbHidi3MbpkzM2N66P-9hObvFCdc2Cn8Hwp1FSwg0>







Interested in sponsoring or a custom webinar to our audience of international investors and startups? Click here<mailto:darina@axisinnovation.com?subject=Sponsor%20Axis%20Webinar>.














[https://bucket.mlcdn.com/a/199/199499/images/4f8ab2a8a9b058d0c9a4ef7eceb5957029c46bc2.jpeg/963bfec248e78800e2fecbbcc593bd102e607067.jpeg]

Best,
Darina Khanina

Business Development Associate

[https://bucket.mlcdn.com/images/icons/contacts/black/email1.png]<mailto:darina@axisinnovation.com>     darina@axisinnovation.com<mailto:darina@axisinnovation.com>









        [Share on Facebook]  <https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2NzgmZD10OWM5ZDF6.OJF3wL-DsEG8AghpC64nXREXS9FxVnN_gs0ny55fDm4>             Share on Facebook <https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2ODAmZD1nM3E5bjVk.ORuyWq8sYkeFBwnr0ADPbvZ9IzxQJGc2HQqsjvEHzKc>                        [Share on Twitter]  <https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2ODImZD12MXczcDBp.rObKLkUMgWReWQIzpg-sG7YR9d6EOzb-2bTd3XkyvHc>              Share on Twitter <https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2ODQmZD13N2o5ajZn.B_FX2sF0A4WP25BcP1uoKDtBul1wvSxdq1wqu6Ki6zY>                         [Forward email]  <https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2ODYmZD1xN2I1bjZp.uHPqH-FGRDvSMzkN-sObPmAWDZSSO_K9v9btSa_kWG4>                 Forward email <https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE2ODgmZD1lN3I0eTV3.Va_CkHZ9x4Bx8_fO19Rg4qKmsMOGQ2gOC_1OEsX0mEc>



Axis Innovation

Ha Ta'asiyah 9, Tel Aviv
Israel



You received this email because you signed up on our website or made a purchase from us.



Unsubscribe <https://click.mlsend.com/link/c/YT0xNDIzMjEyMzI3Mzg5MzY1NjAxJmM9aDFmMCZlPTAmYj0zNDg4NjE3MzQmZD1jNmM0bzRw.fmLaqbyAPXpJAek8nuKYHhjV-JJHhiFhpzXuTK2r-NQ>

**Comment by yurygodyna** [comment]
С уважением,
Годына Юрий

От: aisaev@intact.ru
Отправл.: 22 июля 2020 г. 19:32
Кому: ygodyna@facemetric.ru
Тема: материалы по сервисной модели


Юра, привет!

Направляю тебе материалы по сервисной модели: https://share.intact.ru/apps/files/?dir=/%D0%A1%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D0%BD%D0%B0%D1%8F%20%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C/%D0%9F%D0%BE%D0%B3%D1%80%D1%83%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5&fileid=302652


С уважением,
Александр Исаев
Менеджер отдела управления проектами
Департамент управления проектами

INTACT. Правильный интегратор

+7 (495) 989 40 49 доб. 2519
+7 (915) 229 28 70
aisaev@intact.ru
<mailto:aisaev@intact.ru>
121609, г. Москва,
Осенний бульвар, д. 23
www.intact.ru

[cid:image001.png@01D6605E.DA8D6460]<https://www.intact.ru/>

**Comment by yurygodyna** [comment]
С уважением,
Годына Юрий

От: dpanin@intact.ru
Отправл.: 7 августа 2020 г. 14:52
Кому: ygodyna@facemetric.ru
Тема: RE: Проектная альтернатива


Это ррц, скидка в зависимости от суммы проекта 30-35%


С уважением,
Дмитрий Панин

+7 (495) 989 40 49 доб. 1125
+7 (916) 945 62 92

From: Godyna Yury <ygodyna@facemetric.ru>
Sent: Friday, August 7, 2020 2:46 PM
To: Panin Dmitry <dpanin@intact.ru>
Subject: Re: Проектная альтернатива

Это ррц?
Скидку какую дадут?


С уважением,
Годына Юрий
От: dpanin@intact.ru<mailto:dpanin@intact.ru>
Отправл.: 7 августа 2020 г. 14:18
Кому: ygodyna@facemetric.ru<mailto:ygodyna@facemetric.ru>
Тема: RE: Проектная альтернатива



[cid:image001.png@01D66CCA.62DA8510]

НОВИНКА


DS-2CD3656G2T-IZS(2.7-13.5mm)

311313261<tel:311313261>

5Мп уличная цилиндрическаяIP-камера с EXIR-подсветкой до 60м
1/2.7" Progressive Scan CMOS; моторизированный вариообъектив 2.7-13.5мм; угол обзора 101°- 31°;механический ИК-фильтр; 0.003лк@F1.4<mailto:0.003лк@F1.4>; auto Iris; сжатие H.265/H.264/MJPEG/H.265+/H.264+; тройной поток; 2688×1520@25к/с; WDR 120дБ, 3D DNR, BLC, ROI; Smart видеоаналитика; слот для microSD до 256Гб; аудиовход/выход 1/1; тревожные вход/выход 2/2; 1 RJ45 10M/100M Ethernet; DC12В± 25%/PoE(802.3at); 18Вт макс; -40 °C...+60 °C; IP67; IK10; вес 1.3кг.
захват лиц + детекция наличия маски

28 490 ₽


Отправлено с iPhone



С уважением,
Дмитрий Панин

+7 (495) 989 40 49 доб. 1125
+7 (916) 945 62 92

From: Godyna Yury <ygodyna@facemetric.ru<mailto:ygodyna@facemetric.ru>>
Sent: Friday, August 7, 2020 1:18 PM
To: Panin Dmitry <dpanin@intact.ru<mailto:dpanin@intact.ru>>
Subject: Проектная альтернатива

Привет!

Можешь узнать проектную альтернативу для такой камеры: https://hikvision.ru/product/ds_2cd2743g0_izs
Интересует РРЦ и наша цена на нее
И по этой камере также можно предложение о скидке запросить

С уважением,
Юрий Годына
Генеральный директор

facemetric

+7 499 229 64 22 доб. 4001
+7 903 169 41 80
ygodyna@facemetric.ru<mailto:ygodyna@facemetric.ru>

121609 , г. Москва,
Осенний бульвар, д. 23
facemetric.ru<http://facemetric.ru/>

[signature_2138368467]

**Comment by yurygodyna** [comment]
С уважением,
Годына Юрий

От: skonstantinov@intact.ru
Отправл.: 28 августа 2020 г. 13:06
Кому: ygodyna@facemetric.ru
Тема: FW: Запрос коммерческого предложения


Юра, привет.
У нас есть презентация такого типа?
Спасибо.

С уважением,
Сергей Константинов
Менеджер по работе с клиентами
Департамент продаж

INTACT. Правильный интегратор

+7 (495) 989 40 49 доб. 2016
+7 916 094 27 50
skonstantinov@intact.ru
<mailto:skonstantinov@intact.ru>
121609, г. Москва,
Осенний бульвар, д. 23
www.intact.ru

[cid:image002.png@01D67D3C.0EA0B050]<https://www.intact.ru/>
↓<https://share.intact.ru/s/HLQbjQpR07SEvPI> Презентация о компании<https://share.intact.ru/s/HLQbjQpR07SEvPI>

From: Бланкина Мария Сергеевна <Blankina.MS@gazprom-neft.ru>
Sent: Friday, August 28, 2020 10:26 AM
To: Konstantinov Sergey <skonstantinov@intact.ru>
Cc: Беспалов Сергей Владимирович <Bespalov.SVl@gazprom-neft.ru>
Subject: Запрос коммерческого предложения

Уважаемый Сергей Константинович,
Дирекция переработки и сбыта ООО «Газпромнефть-Цифровые решения», являющаяся клиентской дирекцией Блока Логистики, Переработки и Сбыта ПАО «Газпром Нефть» формирует пул подрядчиков для реализации будущих проектов по видеоаналитике.
Просим Вас в срок до 07.09.2020 прислать презентацию Вашей компании, в которой был бы отражён опыт и возможности Вашей компании в реализации проектов по видеоаналитике на промышленных объектах, проектах, реализуемых в контуре промышленной безопасности, безопасности дорожного движения.
Следующим шагом будет знакомство команды проекта со стороны Заказчика и компанией-подрядчиком.  Дата, время и формат которого будет определён позже.
Контактное лицо:
Бланкина Мария Сергеевна, эл. почта: Blankina.ms@gazprom-neft.ru<mailto:Blankina.ms@gazprom-neft.ru>, моб. тел.: +7 (987) 929-73-70
Беспалов Сергей Владимирович, эл. почта: Bespalov.SVl@gazprom-neft.ru<mailto:Bespalov.SVl@gazprom-neft.ru>, моб. тел.: +7 (921) 983-57-03


С уважением,

БЛАНКИНА Мария Сергеевна
Специалист
Департамента аналитических и поддерживающих систем
Дирекция переработки и сбыта

ООО "Газпромнефть - ЦР"
Россия, г. Санкт-Петербург, Киевская ул.5, БЦ «ЭНЕРГО» каб.408
Моб: +7 (987) 929-73-70
Тел: +7 (812) 448-2401 доб. (061) 42804
ds.gazprom-neft.ru
