### ISSUE TITLE
OpenCV Error: Assertation Failed

### ISSUE THREAD

**Issue by jelimoore** [ageitgey/face_recognition#104]
* face_recognition version: whatever's in the VM
* Python version: 3
* Operating System: Ubuntu 16.04

### Description

I am attempting to use the facerec_faster script in the prebuilt VM. It fails with the following error. I am using a Logitech C615 camera and VMware Workstation.

### What I Did

```
deeplearning@deep-learning-virtual-machine:~/Desktop/face_recognition examples$ python3 facerec_from_webcam_faster.py 
select timeout
select timeout
OpenCV Error: Assertion failed (!buf.empty() && buf.isContinuous()) in imdecode_, file /home/deeplearning/opencv-3.2.0/modules/imgcodecs/src/loadsave.cpp, line 562
Traceback (most recent call last):
  File "facerec_from_webcam_faster.py", line 28, in <module>
    ret, frame = video_capture.read()
cv2.error: /home/deeplearning/opencv-3.2.0/modules/imgcodecs/src/loadsave.cpp:562: error: (-215) !buf.empty() && buf.isContinuous() in function imdecode_

```

**Comment by ageitgey** [comment]
Basically "select timeout" means Ubuntu in the VM isn't able to access your virtual webcam provided by VMware Workstation.

First, make sure you've gone into the VMware Workstation settings and enabled your Webcam so that the virtual machine has access to it. Make sure VMware is actually about to get a picture from your webcam.

After that, you might try the suggestion in this post inside of the virtual machine: https://stackoverflow.com/questions/12715209/select-timeout-error-in-ubuntu-opencv

**Comment by jelimoore** [comment]
Ok, I do USB pass through - I don't mess with virtual webcam stuff. I will try that solution suggested in the stack overflow link. Thanks.

**Comment by jelimoore** [comment]
Ran the modprobe command from stackoverflow - this is what I get.
`deeplearning@deep-learning-virtual-machine:~/Desktop/face_recognition examples$ python3 facerec_from_webcam_faster.py 
OpenCV Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /home/deeplearning/opencv-3.2.0/modules/imgproc/src/imgwarp.cpp, line 3492
Traceback (most recent call last):
  File "facerec_from_webcam_faster.py", line 31, in <module>
    small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)
cv2.error: /home/deeplearning/opencv-3.2.0/modules/imgproc/src/imgwarp.cpp:3492: error: (-215) ssize.width > 0 && ssize.height > 0 in function resize`

**Comment by ageitgey** [comment]
Basically that still means your webcam still isn't working correctly in Ubuntu. It's returning an empty image so the script fails.

This is really an Ubuntu config question separate from this project. To test the webcam, you can install Ubuntu's webcam software 'cheese':

`sudo apt-get install cheese`

And then run that to test if the webcam itself is working before you try to run the script.

Personally I've had better success with configuring the webcam in the host OS and using the VMware virtual webcam instead of trying to use usb pass through to Ubuntu.

**Comment by lidedongsn** [comment]
use usb3.0
