### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by paulaceccon** [ageitgey/face_recognition#115]
* Python  version: 3.6
* Operating sytem: Win 10

### Description

I'm trying to install face_recognition. I've already have dlib in my machine, but face_recognition tries to reinstall it and I don't know why or if I can prevent this.

### What I Did

 It first give me errors with cmake, which I installed. Then, with boost, which I have also installed. I have also set the environment variables which doesn't seem to change the output at all:

![capture](https://user-images.githubusercontent.com/4854694/27708632-f795d81e-5cef-11e7-9cd3-54307a805496.PNG)

 CMakeLists.txt:6 (include)
  -- Could NOT find Boost
  -- Could NOT find Boost
  -- Found PythonLibs: C:/Users/paula.ceccon.ribeiro/AppData/Local/Continuum/Anaconda3/libs/python36.lib (found suitable version "3.6.1", minimum required is "3.4")

I wonder if I can somehow "tell" face_recognition that I have dlib in my machine already.

**Comment by ageitgey** [comment]
Please see #89. This is the same issue.

The issue is that the Windows conda package for `dlib` doesn't register itself in a way that `pip` can see, so it tries to re-install another copy of `dlib` since it thinks it is missing. 

You can work around this by installing `face_recognition` without automatically installing it's dependencies:

```
pip install --no-dependencies face_recognition face_recognition_models
```

But keep in mind that no dependencies at all are installed this way. So if you run into any errors about any missing libraries besides `dlib`, you might need to manually install those libraries with `pip install library_name` as well.

**Comment by jahangeerMirza** [comment]
after executing the above mentioned command I'm getting this error

import face_recognition
....
ModuleNotFoundError: No module named 'dlib'

**Comment by rafraga** [comment]
me too

**Comment by rafraga** [comment]
I'm also having the same problem ("ModuleNotFoundError: No module named 'dlib'"), tried to install dlib on many different ways, but couldn't make it work

**Comment by avanibhatnagar** [comment]
Were you guys able to figure out how to get rid of the "No module named 'dlib'" issue?

**Comment by hay318** [comment]
For me, I had to remove Anaconda then do `pip install --no-dependencies face_recognition face_recognition_models`.
