### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.neighbors.classification'

### ISSUE THREAD

**Issue by DirkWuerdemann** [ageitgey/face_recognition#1262]
* face_recognition version: 1.3.0 ( in script it shows 1.2.3 )
* Python version: 3.9.1
* scikit-learn : 0.24.0
* Operating System: Windows 10

### Description

The pickle.load does not work. It gives the error message that their is No module named 'sklearn.neighbors.classification'

### What I Did

I am using the example code

**Comment by nadsur** [comment]
does your problem solved?

**Comment by diamondbarcode** [comment]
you may try install scikit-learn

https://scikit-learn.org/stable/install.html

**Comment by DirkWuerdemann** [comment]
hi guys,
thx for the hint. In the meantime my problem is solved. After a complete retaining it works.
thx again
Dirk

**Comment by DirkWuerdemann** [comment]
hi guys,
thx for the hint. In the meantime my problem is solved. After a complete retaining it works.
thx again
Dirk

**Comment by BenjaminArmijo3** [comment]
how do you solve it


> hi guys,
> thx for the hint. In the meantime my problem is solved. After a complete retaining it works.
> thx again
> Dirk

**Comment by DirkWuerdemann** [comment]
Hi Benjamin,
i have deletet the knn file and done a new training run. Than it works.
Dirk

**Comment by mimocha** [comment]
**sklearn.neighbors.classification was renamed to sklearn.neighbors._classification in version 0.22.X  
Downgrade to scikit-learn version <= 0.21.3 to fix this problem**

---

A little late to the party here, but I am having a similar problem, so I'll leave this for posterity purposes.

I'm trying to load an older Scikit-Learn KNN classifier model with pickle, but it's throwing the error:
`No module named 'sklearn.neighbors.classification'`, despite the fact that I have the _latest version_ of scikit-learn installed and imported.

Since I am working with older code, I suspected this to be a version compatibility problem. So I did a little digging, and apparently scikit-learn changed the name of their file `/sklearn/neighbors/classification.py` to `/sklearn/neighbors/_classification.py` in [**version 0.22.X**](https://github.com/scikit-learn/scikit-learn/tree/0.22.X/sklearn/neighbors) (See [version 0.21.X](https://github.com/scikit-learn/scikit-learn/tree/0.21.X/sklearn/neighbors) in comparison)

So I downgraded my scikit-learn installation to 0.21.3, which successfully fixed the problem.

**Comment by aidynabirov** [comment]
> **sklearn.neighbors.classification was renamed to sklearn.neighbors._classification in version 0.22.X Downgrade to scikit-learn version <= 0.21.3 to fix this problem**
> 
> A little late to the party here, but I am having a similar problem, so I'll leave this for posterity purposes.
> 
> I'm trying to load an older Scikit-Learn KNN classifier model with pickle, but it's throwing the error:
> `No module named 'sklearn.neighbors.classification'`, despite the fact that I have the _latest version_ of scikit-learn installed and imported.
> 
> Since I am working with older code, I suspected this to be a version compatibility problem. So I did a little digging, and apparently scikit-learn changed the name of their file `/sklearn/neighbors/classification.py` to `/sklearn/neighbors/_classification.py` in [**version 0.22.X**](https://github.com/scikit-learn/scikit-learn/tree/0.22.X/sklearn/neighbors) (See [version 0.21.X](https://github.com/scikit-learn/scikit-learn/tree/0.21.X/sklearn/neighbors) in comparison)
> 
> So I downgraded my scikit-learn installation to 0.21.3, which successfully fixed the problem.

Thanks ! It worked

**Comment by pipashu1** [comment]
> 

Thx ! My problem is " No module named 'sklearn.neighbors._classification'" . It also worked .
