### ISSUE TITLE
Raspberry Pi Memory Error

### ISSUE THREAD

**Issue by oguzhankarabulut** [ageitgey/face_recognition#159]
* face_recognition version: 02.1
* Python version: 2.7
* Operating System: Raspian

### Description

I installed to face_recognition my raspberry pi successfully for python 3. Now i am trying to install for Python2 because i need it. When i was trying install i am taking a Memory Error. I attached the images from my error. Please help me 

![20170821_190454](https://user-images.githubusercontent.com/23421095/29530146-1e98e7be-86ab-11e7-91ea-e17c02170f63.jpg)
![20170821_190501](https://user-images.githubusercontent.com/23421095/29530148-2113ac22-86ab-11e7-934d-e2062359f51a.jpg)

**Comment by ageitgey** [comment]
Check out the README [here](https://github.com/ageitgey/face_recognition#common-issues).

**Comment by Palakshi123** [comment]
Hey,

This error is occurred because caching mechanism is trying to read entire file into memory before caching.

To solve this error, run the below code on terminal.

Sudo nano/etc/dphys.swapfile
CONF_SWAPSIZE = 1024 #change size
Sudo /etc/init.d/dphys.swapfile start
Sudo /etc/init.d/dphys.swapfile stop
