### ISSUE TITLE
CNN model dead accurate if i use the same photo

### ISSUE THREAD

**Issue by eloelo22** [ageitgey/face_recognition#169]
* face_recognition version: current version
* Python version: version that came with the current version of face_recognition
* Operating System: Ubuntu 16.4

### Description

i am currently testing the cnn model i am in fact amaze at the accuracy, In my project i am trying to achieve the result that can be put this way "that guy looks like the other guy" using the hog model i have that kind of result. Now in using the cnn i uploaded up to 5 photos of the same person then uploaded a photo that is the same photo from one of the 5 previously uploaded in hog model the result would include all the photos with tolerance set to default but using the cnn model i only get a single result. is that how it is supposed to be when using the cnn model? 

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
I don't totally understand the question. The choice between the HOG model and the CNN model only affects face detection, not face recognition. So using the CNN model shouldn't really affect things the way you describe. If you could post some sample code showing the issue, that would help me understand the question better.

**Comment by eloelo22** [comment]
sorry if you didn't understand my question.can i use the cnn model for face comparison?

**Comment by eloelo22** [comment]
i am doing a face compare using the face_encoding but when i saw the sample with the cnn model i tried to do a face_compare with a single unknown photo to that of 5 known (all the photos belong to the same person)  when using the hog model i get all the known photos with respective distances but when i use the cnn model to do a face compare it returns a single result

**Comment by ageitgey** [comment]
No, the CNN model and the HOG models you are talking about are different ways of *detecting* faces (finding faces in a photo). They aren't face recognition models.

There's only one face recognition model in this library. No matter how you detect the faces in the image, the actual face recognition step (i.e. the `face_encodings()` function and then the `compare_faces()` function) is always done with a CNN. But that face encoding CNN model is totally separate from the face detection CNN or face detection HOG model you are talking about.

So that's why your question is confusing. There's not two different face recognition models to choose between. There's just the one. The only choice between models is for the face *detection* step.

**Comment by eloelo22** [comment]
last question when i invoke the face_location and store it as csv file and later use it for face_compare i do get a single result is it ok to use the face_location rather than face_encoding?

**Comment by ageitgey** [comment]
`face_location` is just the x/y co-ordinates for where the face is located in the image. It's just four numbers - the top, bottom, left and right sides of a box around the face.

`face_encodings` gives you a numerical representation of the structure of a face. This is the only thing you can compare with `compare_faces`. 

They are totally separate things. You can't mix and match them. 

Comparing the face locations with `compare_faces` doesn't make any sense because all you would be comparing is where the faces appeared in the image, not anything about the structure of the faces themselves.

**Comment by eloelo22** [comment]
thank you so much for the clarification i got as far as learning python to make a webApi for face comparison
