### ISSUE TITLE
Side view faces

### ISSUE THREAD

**Issue by diafatu** [ageitgey/face_recognition#208]
Does this algorithm detect side view faces in images too? I am looking for one to implement for TP-GAN.(Beyond face Rotation Paper)

**Comment by ageitgey** [comment]
It's not trained to recognize side view faces, so it probably wouldn't work well for that use case unfortunately.

**Comment by michaelmano** [comment]
@ageitgey How would we go about trying to train it for this?

I'm new to python and the whole machine learning side of things and I'm just curious if there could ever be a feature for this or if you know of any other libraries for this?

**Comment by ageitgey** [comment]
If you just want to detect side-view faces, you could create a bunch of training data and train an object detector like this: http://blog.dlib.net/2016/10/easily-create-high-quality-object.html. That wouldn't be too hard to do. That's the same way the frontal face detector works.

If you want facial *feature* detection (eyes, nose, etc) and face recognition with side view faces, it would be a lot more work.

**Comment by michaelmano** [comment]
Thanks for getting back to me and the link to the tutorial 👍

**Comment by prateekmantha** [comment]
@ageitgey, the face_recognition is great! But I also want to be able to recognise side faces. I have implemented the side face detection and could also do the side face recognition using a neural network separately from this model. But your model works so well that I want to be able to integrate side face recognition with the existing frontal recognition. Right now I'm stuck because I cannot find much information on how the encodings are generated from the front faces and if you could suggest me something it would be great.

**Comment by richardARPANET** [comment]
For detection (but not recognition) of side faces, this lib works very well and is much faster than face_recognition https://github.com/arunponnusamy/cvlib

**Comment by 7thstorm** [comment]
Hi all!
I'm running into issues with dlib and side face detections. For some reason, even for side faces,m dlibs returns all 68 landmarks, and then my cnn tries to recognize this face. I am setting it up, so if landmarks < 45, to ignore detections, but since everything is being returned as 68, my system tries to recognize, and fails miserably.
Is this a dlib issue? or is it something I'm doing??
Really, all I want to do is dlib to return back an accurate number of landmarks detected. Can anyone comment?
ps. not looking for recognition, only detection

**Comment by nyck33** [comment]
@7thstorm I am trying to build a side face detector myself.  Do you have any code you can share and I can try to see why that is occuring.

**Comment by fadi212** [comment]
@ageitgey it does work on side view face but only in case of detection. I have performed it. But can you please help if there is any way we can train it to RECOGNIZE side view faces or is there any way that we collect some images in different position with angle lets say about 30 degree. It is possible ?

**Comment by nyck33** [comment]
I think the solution is to train 2 different detectors.  Maybe one cannot detect both frontal and side/profile.  And then run the image through the 2 networks.  Here are training parameters for another dlib model.  https://github.com/Luca96/dlib-minified-models/tree/master/face_landmarks#training-parameters

**Comment by nyck33** [comment]
@fadi212 
https://github.com/ageitgey/face_recognition/issues/421#issuecomment-524605899
do you want to work on this together?
I have unlimited free access to GTX 1080 GPU for this.

**Comment by Shalomjohn** [comment]
@nyck33 did you succeed in solving this?

**Comment by nyck33** [comment]
No, my contract ended so I never finished.  It shouldn't be that hard to train from scratch though.  Just time consuming if you have to annotate your own dataset.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
