### ISSUE TITLE
How to fix this error?

### ISSUE THREAD

**Issue by semen7907** [ageitgey/face_recognition#212]
TypeError: unsupported operand type(s) for -: 'list' and 'numpy.ndarray'

code with an error:

known_face_encoding = [rec[1]]   (rec [1] - array from the database)
match_results = face_recognition.compare_faces(known_face_encoding, unknown_face_encodings[0],tolerance=0.6) #error

**Comment by ageitgey** [comment]
It depends on the data type of your array from the database. Maybe this would work:

```
import numpy as np

known_face_encoding = np.array(rec[1])
```

**Comment by semen7907** [comment]
I did so, gives such a message: 
TypeError: len() of unsized object

**Comment by semen7907** [comment]
This is how the array looks in the database:
<a href="https://ibb.co/nMfLd6"><img src="https://preview.ibb.co/kHDvBR/image.png" alt="image" border="0"></a>

**Comment by semen7907** [comment]
please add a sample script with DB

**Comment by ageitgey** [comment]
If you have a script that can reproduce the issue, feel free to share it. Otherwise, there's no good way to answer this question in a generic way. The exact code is going to depend on the database you are using and the database library you are using to access it. Using a database to store and load data is really a separate issue outside the scope of this library.
