### ISSUE TITLE
An optimized example similar to "facerec_from_webcam_faster.py" for Raspberry Pi 

### ISSUE THREAD

**Issue by noblekoshy** [ageitgey/face_recognition#213]
* Operating System: Raspbian  Stretch on RPi 3 Model B + RPi Camera 

### Description
To preface, sorry if this is more of Raspberry Pi question than a face_recognition issue. Was not sure where else to post this. 

I successfully got face_recognition working on my Pi 3 following the steps listed here. The "facerec_on_raspberry_pi.py" example works well. Reducing the image size and camera resolution definitely improves performance. I want to do something similar with the "facerec_from_webcam_faster.py" example using the RPi Camera. I have the OpenCV installed. With the addition of V4L2 driver support the RPi Camera can be accessed like a webcam. So the command "cv2.VideoCapture(0)" works with the RPi Camera. So I can run the "facerec_from_webcam_faster.py" on my RPi but not at a great framerate.  

So I was wondering how I can improve performance. I would need to lower the camera resolution (not sure of how to code this).  Also, would it be better to use the "picamera" module?

**Comment by ageitgey** [comment]
You can lower the resolution further by changing [this line](https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam_faster.py#L31). Instead of scaling the image down to 25% size (with 0.25), you could go smaller with a value like 0.12 or whatever. 

Make sure you compiled dlib on your RPi with the Neon extensions enabled. It requires passing an extra flag with you compile dlib (i.e. `sudo python3 setup.py install --compiler-flags "-mpfu=neon"`). Neon is the ARM CPU extensions to speed up vector math. It will make a pretty good difference in speed on RPi. 

Also, I would compile OpenCV itself with Neon enabled - see [this post](https://www.pyimagesearch.com/2017/10/09/optimizing-opencv-on-the-raspberry-pi/).

I don't know if using picamera is faster or slower than cv2.VideoCapture(0). You could try it both ways. Both libraries just give you back a numpy array, so the rest of the code is the same after you get an array of image data from the camera.
