### ISSUE TITLE
Clustring data 

### ISSUE THREAD

**Issue by EssamEid614** [ageitgey/face_recognition#215]
I was using the library and i was wondering if there is any possible way to cluster the data of the extracted face encoding to be able to search through them quickly for similarity ? The documentation doesnt show anything about these extracted encodings or how to cluster them

**Comment by AlainPilon** [comment]
How many thousand of faces do you have? How fast do you -really- need it to be? Because unless you find it slow now, you are talking about an hypothetical issue which may never happen. 

The comparison is done in a Numpy Array, which is extremely fast.

**Comment by EssamEid614** [comment]
Well right now i have 13 thousand encodings and it takes about 12 seconds to go through all of them , however its expected that this data hits millions of records

**Comment by AlainPilon** [comment]
Ok, you are a level of magnitude higher than me ;-)

Stupid question, but are you sure the comparison is using an numpy Array and not a List?

Also, I dont know your business case, but what I am planning to do on my end to speed things up eventually is to maintain multiple lists, based on some situational data from my users. This is a guess but I doubt Facebook compare all the faces in a pictures against their whole face library. Instead they only test it against a small subset (you friends, friends of friends and people who happened to be in the same location when the picture was taken). Maybe you can do something similar. 

Other ideas: 
- split your library in two by gender for a 100% speed gain
- maybe write face_recon to use numba (https://numba.pydata.org/) instead of numpy so it can use the GPU (never tested numba, but it is on my list!)
- monitor your system to see if you have a hardware bottleneck.

**Comment by EssamEid614** [comment]
yea i am pretty sure i used debug mode to verify this and it is an ndarray
also that split on male and female is a pretty good idea thanks ! 
however i would still like to know what these face encodings represent what is the meaning of the numbers , if i can get a better understanding of the numbers , i might be able to cluster the data even more for faster response

**Comment by AlainPilon** [comment]
@EssamEid614 @ageitgey made a series of blog post on medium that are fantastic to understand the underlying principles: https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78

As I said, I dont know your use case, but another way you can split this would be to determine if it is possible to dynamically split the encodings on another mutually exclusive attribute (gender was one). Like if you known the location of the person who is submitting the image, you can only try to match against people in the same region. Also, if you notice that 80% of your checks are dones against the same 20% of encodings, you can make a smaller set of only these and try to match there first with a more restrictive threshold and if it fails, match against the whole set.

Time to be creative ;-)

**Comment by EssamEid614** [comment]
@AlainPilon sorry for the late reply but you do make a solid point , i am actually now considering to give the encodings to a machine learning algorithm ( specifically K-means ) for unsupervised learning against some huge dataset of 100,000 faces or more and let it train and cluster the data to four clusters for example and only roll through all cluster if no appropriate match was found against the first , meaning if not found in the first go to second not in second go to third etc. if it got trained well it should provide somewhat better performance against 4 clusters of encodings .
thanks for your help really appreciate it !
