### ISSUE TITLE
Face Recognition questions

### ISSUE THREAD

**Issue by lezabour** [ageitgey/face_recognition#234]
Hi,
Sorry not really an issue, more a question, but don't know how to ask except here ;)

* face_recognition version: last (install 2 days ago)
* Python version: 2.7 & 3
* Operating System: Raspbian (raspberry pi 3)

### Description
I'm having a question about face recognition. I used to do it with opencv 2.9, we had to have several pictures for each person in the dataset, align all faces, and train the classifier for our dataset.

So i install on my PI3, the face_recognition librairie, opencv 3.3 (with dnn/dlib etc.) to try the new technic with machine learning

As per your example here, with machine learning & face_recognition new librairie, you ask only 1 picture per person, and not only the face.
Is it enough?
Don't we need several faces pictures, and aligned, to make it work properlly?

For sure i have a good result, when only test with Barack Obama, but what about when their is 100 people in dataset? with some brothers/sisters, that look alike etc...
Don't we need more picture to build and train dataset?

Thanks for help

**Comment by AlainPilon** [comment]
Asked a few times before: https://github.com/ageitgey/face_recognition/issues/217

Basically, this is not a neural network: it does not need to be trained. 

And as long as you dont have identical twins, it should be able to tell the difference between siblings without much problem.

**Comment by 2017TJM** [comment]
for this example i can do what

**Comment by tharssh** [comment]
is this not convolution neural network?

**Comment by AlainPilon** [comment]
we are using a pre trained model, read this excellent article, it explains everything: https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78

**Comment by lezabour** [comment]
Hi 
Thanks for your answer.
I have followed few weeks ago the "machine learning is fun part4"
Hey,
thanks for answer.

And i can see a big difference, but don't (yet) understand why.
In your previous way to work (part4), we still have to have several pictures for one guy.
We can improve it, by adding more pictures, so we have a better model.

So, if this one does not need to be train, i have a big question ;)
How does it improve himself?
 if i have a false positive, or false negative, how do i "train" it to learn better? (knowing that there is no "learning.."
But this is more a "conceptual" question than code-production.

thanks

**Comment by AlainPilon** [comment]
> How does it improve himself?
it does not! 

This is where things can get interesting and you can get creative! If you use a small tolerance, odds are that any match will be a valid one, but you will reject more valid results. In this case, you can have these reject go thru another round of analysis using a totally different system. 

As stated by @ageitgey a classifier could do a good job (and could be trained) but before throwing all misses there, I would do another round of encoding comparisons but this time using a high tolerance. In this case, any misses would mean that we really dont know who the picture belongs to and remove it from the classifier analysis (keep it in a separate list for future matches). 

The reason we want to remove them from the classifier is that classifier will force a match, even if it is a bad match since by definition they have to put each input into a class. 

Hope this clearer things out a bit!

**Comment by ashacs12** [comment]
Hi,
how can we achieve face recognition part to train on our datasets? Kindly help.

**Comment by pypower-codes** [comment]
Honestly speaking, I don't think that there is any possibility to distinguish identical twins just based on facial photographs. This is particularly true when you want to be able to recognize them in adverse conditions, e.g., difficult illumination, low resolution and alike.
Just think about how humans would distinguish twins. _They would not rely on the facial images, but on other behavioral traits that are not available in the images._
**If the information is not inside the images, you cannot extract the information.** Hence, there is very little chance that any purely image-based algorithm would be able to distinguish twins.
