### ISSUE TITLE
Is there a way to assign a confidence value to face similarity?

### ISSUE THREAD

**Issue by jobini** [ageitgey/face_recognition#241]
* face_recognition version: latest
* Python version: 3.5
* Operating System: Ubuntu 16.04

### Description

I wish to compare two faces and assign a confidence value to it. For instance, two face images of the same person would have a confidence value of 100, while comparing faces of different people would give me values in [0,100). 

Currently, the face_distance function computes the Euclidean distance between two face vectors. Is there a way I can associate a confidence value to this Euclidean distance? 

My gut feeling is that this isn't possible because Euclidean distance is unbounded (since it's a norm), unless the individual coordinates of the face vectors are bounded.  

Would it be wise to compare the similarity of face vectors using the absolute value of the cosine similarity, as there's a rather straightforward way of assigning a confidence value to it (since absolute value of cosine similarity is in [0,1], I just need to multiply by 100, which would give a crude percentage value)?

**Comment by ageitgey** [comment]
If instead of calling `face_recognition.compare_faces()`, you instead call `face_recognition.face_distance()`, that will return the euclidean distance between each possible match and the image you are testing. That's the closest thing to a confidence value there is. The smaller the number, the closer the match. The default cutoff for a "match" is 0.6.
