### ISSUE TITLE
C++ Support

### ISSUE THREAD

**Issue by SriramEmarose** [ageitgey/face_recognition#256]
Hi All,

It is a great work. Thanks for the efforts. It is giving really good results.

One doubt is, Is there any API for the same library in C/C++?
Though it is derived from Dlib, I hope the "FaceRecognition" function that Dlib offers is different from this implementation.

Would be a great help if you could point me to any such API calls if available.

Thanks,
Sriram

**Comment by ageitgey** [comment]
If you want to use C++, just use dlib directly since C++ is what it's mainly designed for. See http://dlib.net/dnn_face_recognition_ex.cpp.html

The goal of this library is just to make face recognition super easy in Python and to provide an off-the-shelf solution that "just works" as much as possible (models automatically included, lots of examples, etc). But dlib is still doing all the face encoding and face detection work, so you should get the same results if you use the dlib's C++ api directly.

Some day this library may pull in alternate face detection/encoding models from outside dlib if needed, but that's not currently the case.

**Comment by SriramEmarose** [comment]
Hi,

Thank you very much for the prompt response. Will check it.

Thanks

**Comment by ageitgey** [comment]
Sure thing :)

**Comment by Jayhello** [comment]
@ageitgey , hello, I use dlib to do face detection (C++ code), core code like below:

```
dlib::frontal_face_detector detector = dlib::get_frontal_face_detector();

std::string img_path = "/data/service/face_rec/face_test/wlj1 (1).jpg";
dlib::array2d<unsigned char> img;
dlib::load_image(img, img_path);

std::vector<dlib::rectangle> dets = detector(img, 1);


```

I found the above code is about 5 times slow than  python interface, do you know why?

**Comment by Carbonil** [comment]
@Jayhello Seriously?.This code is 5 times slower than python interface?.wow?.have you find the reason behind it?

**Comment by creatist** [comment]
> @ageitgey , hello, I use dlib to do face detection (C++ code), core code like below:
> 
> ```
> dlib::frontal_face_detector detector = dlib::get_frontal_face_detector();
> 
> std::string img_path = "/data/service/face_rec/face_test/wlj1 (1).jpg";
> dlib::array2d<unsigned char> img;
> dlib::load_image(img, img_path);
> 
> std::vector<dlib::rectangle> dets = detector(img, 1);
> ```
> I found the above code is about 5 times slow than python interface, do you know why?

I found this phenomenon too .I think the C++ API above is not the deep model version. The  Non deep model Python API will 1.5 times slow than this C++ API.

**Comment by creatist** [comment]
I retry the Python face detect API on my Centos server. This time it's very fast 20ms per image, but when i run C++ API on my PC ， it's very slow , about 600 ms per image. I think the reason is that when you run pip command to install dlib, it was built to use multiply CPUs, but when you compile it yourself , you use only one CPU, so it will be very slow.  I thought i was cheated by dlib. It is very slow on single CPU.
