### ISSUE TITLE
Can I compare two image as fingerprint scan?

### ISSUE THREAD

**Issue by esritines** [ageitgey/face_recognition#259]
* face_recognition version: 1.0.0
* Python version: 3.6
* Operating System: Windows 10 64 bit

### Description

I'm doing an assistance system, there are 5000 people who should be assisted but for processing time I can not compare each photo obtained from each person and compare it with the 5000 photos that are in the database.

There is no way to get something similar to a hash code of each of the 5000 images and compare that hash code with the one in the photo taken, I want something similar to the fingerprint.

**Comment by ageitgey** [comment]
The result of the `face_encodings()` function is the 'fingerprint' that represents the face. But it's not exactly a hash code because it will vary a little from image to image. You need to compare the known and unknown encodings by euclidean distance.

Check out this example for one way of doing what you want: https://github.com/ageitgey/face_recognition/pull/250

**Comment by esritines** [comment]
Thanks a lot!
