### ISSUE TITLE
Hog was more accurate than CNN model

### ISSUE THREAD

**Issue by itsmeeChandU** [ageitgey/face_recognition#283]
* face_recognition version:
* Python version: Python 3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)] on win32
* Operating System: win 10

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did
i tried both cnn and hog on this picture(Worlds largest selfie!! ;) )https://www.windowscentral.com/sites/wpcentral.com/files/styles/larger/public/field/image/2014/11/worlds-largest-selfie.jpg?itok=0mmbRWFo

result : hog detected 33 faces
but CNN only 5
these 2 results are not satisfactory. There are more than 100+ people in the image  
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
There's a minimum size face it looks for so that the execution time is reasonable. Your sample image is pretty low resolution so most of the the faces are too tiny for the default settings and aren't found.

You can control this using the `number_of_times_to_upsample` parameter. If you change it to `number_of_times_to_upsample=2`, it will upscale the image more and find smaller faces but take longer to run.

For example, this code:

```python
face_locations = face_recognition.face_locations(image, number_of_times_to_upsample=2, model="cnn")
```

... finds 130 faces in the image but can take a long time to run.

But a better solution is to work with higher-resolution images that don't have such low-resolution faces.

**Comment by MLDSBigGuy** [comment]
Can i get the accurate face encodings of all those 130 identified faces to compare one face with one another ?

**Comment by ageitgey** [comment]
@MLDSBigGuy If you passed that face_locations array to the face_encodings function, it should give you a face encoding for each one. There's an optional `known_face_locations` parameter you can pass in if you already know the face locations - http://face-recognition.readthedocs.io/en/latest/face_recognition.html#face_recognition.api.face_encodings

**Comment by MLDSBigGuy** [comment]
Thank you :)
