### ISSUE TITLE
Speed of face_detection

### ISSUE THREAD

**Issue by chunkya** [ageitgey/face_recognition#306]
* face_recognition version: 1.0.0
* Python version: 3.5.2
* Operating System: Ubuntu

### Description
I am using face_detection to crop faces from millions of images of varying sizes and running it on GPUs. It works great but I would like to know if resizing the images would speed it up a lot. Would resizing the images to a fixed size and use the batch face detection speed it up a lot? Also, some of the images I am passing through the model can be quite big. Will resizing the image to a smaller size help with the speed too and how would it impact the result of the face_detection?

**Comment by ageitgey** [comment]
- Would resizing the images to a fixed size and use the batch face detection speed it up a lot? 

Yep, probably - especially if you are using a GPU and have a lot of images to process.

- Will resizing the image to a smaller size help with the speed too

Yes, absolutely. This will help a lot in speeding up face detection since the search area is smaller. The bigger the image, the longer it takes.

- and how would it impact the result of the face_detection?

It will miss faces that are too small. So if you resize the image so that the faces themselves are too small of an area in pixels, they will be missed entirely by the algorithm. Just play around with it and see what works well for your data.
