### ISSUE TITLE
cuda error

### ISSUE THREAD

**Issue by lisongjian** [ageitgey/face_recognition#31]
* face_recognition version:   just pip install done
* Python version: 2.7
* Operating System:  ubuntu 14.04
 
### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
Error while calling cudaGetDevice(&the_device_id) in file /tmp/pip-build-2o0Zpt/dlib/dlib/dnn/gpu_data.cpp:178. code: 35, reason: CUDA driver version is insufficient for CUDA runtime version

**Comment by ageitgey** [comment]
This means your CUDA installation is messed up.

Most often this happens if you installed CUDA in the past but then later Ubuntu automatically upgrades the NVidia drivers to a newer version. Sometimes all you need to do is reboot to make sure you are using the latest drivers. Other times you might have to re-install a newer version of CUDA after rebooting.
