### ISSUE TITLE
face_recognition with 3d faces of a person 

### ISSUE THREAD

**Issue by MLDSBigGuy** [ageitgey/face_recognition#310]
* face_recognition version: latest version
* Python version: 3.6
* Operating System: Mac os High Sierra

### Description

Hi :)

Thanks for wonderful simplification of face_recognition.

I used both hog/cnn model with 3d views of my face like central, left and right sides of my face. 

The central face is identified perfectly. Also, the half side views works good. If we assume 180degrees as complete front view of face, 90degrees is complete side view of face. Anything between 120  to 180 degress is identified as face with distance variations. 

But when i give between 90 to 120degrees, the side images are not even identified. I get warning as no faces found, ignoring file.

can i identify the side views of a face as face identified instead of warning as no face found ?

Thank you :)

Queries:
1. Could you please tell me what are the minimum requirements on how the image to be captured ?

2. I used the default model as specified in docs as dlib_face_recognition_resnet_model_v1.dat. Does changing this to another model help me in identifying the side views better ?

3. As a human , i can say that a person is same with his side view after seeing his face color, face hair, face earings or piercings etc., Does models used in this library are already trained with all these features ? If so, why my 90degrees images are not identified as faces ? If not, could you please give me an example of how to train model with these features ?    

PS: I took my images so i could not post them here. But, i can pass them personally if needed.

### What I Did

```
Ran the api.py with different images of my face. 
```

**Comment by MLDSBigGuy** [comment]
Hi :)

Thanks for wonderful simplification.

I used the face_recognition libraray hog model with 3d faces like left and right sides of my face. 
The central face is identified perfectly. But, when i give only the complete left/right sides of my face, the side images are not even identified. I get warning as no faces found, ignoring file. 

can i identify the side views of a face with this library ? 

Thank you :)

**Comment by ageitgey** [comment]
> Could you please tell me what are the minimum requirements on how the image to be captured ?

It's a frontal face detector, so it won't detect side views of faces in most cases.

> I used the default model as specified in docs as dlib_face_recognition_resnet_model_v1.dat. Does changing this to another model help me in identifying the side views better ?

That's the face encoder model for *face recognition* that you are talking about. You are really asking about the *face detection* model which is a separate model. There are two built-in face detection models. You can switch to the second model by passing in `model="cnn"` to the `face_locations()` function. It will probably do a little better on side views of faces. You can see if that works for your data, but no promises that it will.

> As a human , i can say that a person is same with his side view after seeing his face color, face hair, face earings or piercings etc., Does models used in this library are already trained with all these features ? If so, why my 90degrees images are not identified as faces ? If not, could you please give me an example of how to train model with these features ?

It's not trained on side views since that's not really the use case of this library. If you want to build a face detection model that recognizes face side views really well, you'll need to train your own model. You can bypass this module and just use `dlib` directly to do that. This article will get you started: http://blog.dlib.net/2016/10/easily-create-high-quality-object.html

However if you use a CNN model in dlib, you'll have to write or tweak some C++ code to get it done. But there are some good examples in dlib that would work with very minimal tweaking.

**Comment by MLDSBigGuy** [comment]
Thank you :) For my sample images, both cnn and hog are showing almost similar results with cnn taking bit more time. Thanks for the link. I will go through it.
