### ISSUE TITLE
Deeplearning vm Assertion error 

### ISSUE THREAD

**Issue by netrosec** [ageitgey/face_recognition#326]
* face_recognition version: latest
* Python version: 3
* Operating System: deep learning vm (Ubuntu)

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.
IMPORTANT: If your issue is related to a specific picture, include it so others can reproduce the issue.

### What I Did
I simply clicked the face_recognition.py and opened with the editor. I clicked on play button to execute the program and this is error I get: opencv error: Assertion failed ( !buf. empty () && buf.isContinous ()) in imdecode_, file '/home/deeplearning/opencv-3.2.0/modules/imgcodecs/src/loadsave.cpp' , line 562
```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
Traceback (most recent call last):
 file, '/home/deeplearning/Desktop/face_recognition_examples/facerec_from_webcam_faster.py', line 28 in module

cv2 error: home/deeplearning/opencv-3.2.0/modules/imgcodecs/src/loadsave.cpp 562 error : -(215)   !buf. empty () && buf.isContinous ()) in imdecode_

**Comment by ageitgey** [comment]
That probably means that OpenCV isn't able to read a valid image from your webcam. You'll have to investigate if you have your webcam working correctly in OpenCV. Getting your webcam working in Windows with OpenCV is beyond the scope of what I can help you with since it's not really an issue with this library. Maybe some other Windows users can give you suggestions if they had the same issue.

Otherwise, you could try one of the examples that doesn't require a webcam.
