### ISSUE TITLE
How to see the confidence of face detection?

### ISSUE THREAD

**Issue by Arieszhang1994** [ageitgey/face_recognition#329]
* face_recognition version:
* Python version:
* Operating System:

### Description
I can just get the location by `face_recognition.face_locations`
But how can I see the confidence of the face detection?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by ageitgey** [comment]
I don't think confidence of face *detection* is exposed anywhere in the api. So you won't be able to get that from this library. If that was important to your use case, you could write some C++ code using dlib directly to get it.

**Comment by Arieszhang1994** [comment]
Thank you so much for your fantastic work!
In fact,  I just found the example of dlib in 
[http://dlib.net/cnn_face_detector.py.html](url). 
Maybe you can add api of confidence on
line 114 of api.py
`[_trim_css_to_bounds(_rect_to_css(face.rect), img.shape) for face in _raw_face_locations(img, number_of_times_to_upsample, "cnn")]`
By adding `face.confidence`

**Comment by ageitgey** [comment]
I don't think dlib provides confidence values for the other, non-CNN HOG model. So I'm not sure that there is a good way to work it into this API since I couldn't provide the confidence value in both cases.

If your main goal is to only detect faces and you care about confidence values, it might be simpler to just use dlib directly. The goal of this library is more to make the face recognition part simple (by packaging the models, making the api a little simpler, etc).
