### ISSUE TITLE
Improving detection of faces?

### ISSUE THREAD

**Issue by JasonLukose** [ageitgey/face_recognition#333]
* face_recognition version: Latest
* Python version: 2.7
* Operating System: MacOSX

### Description

I would like to be able to detect faces from further away the camera source, is there any parameter that can be changed to help with this?

### What I Did

I am running code to take video from webcam and process frame by frame. The facial detector only recognizes faces once an individual is really close to the camera. I would assume this lies on the part of dlib for facial detection?

**Comment by ageitgey** [comment]
Sure. On [this line](https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_from_webcam.py#L40) of the standard webcam demo, you can change this line:

```python
    face_locations = face_recognition.face_locations(rgb_frame)
```

to this:

```python
    face_locations = face_recognition.face_locations(rgb_frame, number_of_times_to_upsample=2)
```

That will make it look for smaller/further away faces at the expense of running slower by upsampling the original image more. With that setting, I can easily find tiny faces across the room with my computer's webcam.

Note that if you are running the "faster" version of webcam demo, it is down-scaling the image to 1/4 size to speed things up. That will make it a lot worse at finding far away faces. So that particular demo isn't the best if you care about finding all possible faces in the image.

Thanks,

Adam
