### ISSUE TITLE
Can't recognize the photo shooting by iPhone

### ISSUE THREAD

**Issue by RingWong** [ageitgey/face_recognition#381]
* face_recognition version: 1.2.1
* Python version: 3.6
* Operating System: Ubuntu16.04

### Description
When I use the photo that shooting by iPhone, the face can't be recognized.
Is the photo too large?
### What I Did

```
image = face_recognition.load_image_file('test_face.jpg')
face_landmarks_list = face_recognition.face_landmarks(image)
print(face_landmarks_list)
```
The code output is []

**Comment by ageitgey** [comment]
Hi @RingWong,

The issue is that when you take a vertical picture on your iPhone, the iPhone actually stores the image data sideways. It then records an EXIF tag in the image that tells the program reading the image that it needs to rotate the image itself to make it appear the correct way on screen. So when you open the image on your phone or computer, the view program knows to apply this rotation so the picture doesn't look sideways. However, face_recognition doesn't do that rotation automatically. So face_recognition doesn't detect any faces because the image is actually upside down or sideways.

You can find more info on EXIF image rotation here: http://leancrew.com/all-this/2009/04/derotating-jpegs-with-exiftool/

When I get some time, I want to write a little python library that fixes this problem. But you can also google for how to fix exif rotation in python code and find some examples.

**Comment by RingWong** [comment]
Hi @ageitgey ,
With you help, the issue is solved. Thanks a lot!

**Comment by ageitgey** [comment]
No problem! :)
