### ISSUE TITLE
confidence scores

### ISSUE THREAD

**Issue by Vsilent001** [ageitgey/face_recognition#505]
* face_recognition version:1.22
* Python version:3.4
* Operating System:win10

### Description
My purpose is to get the confidence score that tell how much the input image is like human face for all input images.
I would appreciate it very much if you could tell me how to get the confidence scores through using  face_recognition
Thank you!

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Vsilent001** [comment]
Sorry for my ambiguousness!
I am asking for confidence scores on face detection, I want to get the confidence score for any input image.

**Comment by foobargeez** [comment]
> or on face recognition (i.e. confidence about who the face belongs to)?

I am in need of this one too ...

**Comment by ageitgey** [comment]
@Vsilent001 confidence scores on face detection aren't returned in this library because it's intended to be a very simple API. Maybe I can add that somehow in the future. But if you use dlib's CNN face detector directly, it does return confidence scores for each face. Check out this example: http://dlib.net/cnn_face_detector.py.html

@foobargeez scores for face recognition matches are returned by the `face_recognition.face_distance()` function. Check out the [docs here](http://face-recognition.readthedocs.io/en/latest/face_recognition.html#face_recognition.api.face_distance) or any of the face recognition examples.

**Comment by shubhoatdc** [comment]
Hello All. Can anyone give reference to some paper on "Face Recognition Confidence Score". It would be of great help. Thank You.

**Comment by krupeshxebia** [comment]
how do we get confidence score for "face recognition" i.e. By how much value the assigned face name matches with known face name encodings..
