### ISSUE TITLE
Not enough ram for installing dlib on Raspberry Pi 3

### ISSUE THREAD

**Issue by RatchananPrasan** [ageitgey/face_recognition#57]
* Python version: 3.4.2
* Operating System: Raspbian 8.0 ( Raspberry Pi 3 model B )

### Description

I installing dlib and when I run
`python3 setup.py install --yes USE_AVX_INSTRUCTIONS --no DLIB_USE_CUDA`
in Raspberry Pi 3 and ram are not enough to run at 96% "object_detection.cpp.o" .

How to manipulate to install from another device and copy to Raspberry Pi 3

**Comment by ageitgey** [comment]
What exact error did you get?

Side note: Don't enable USE_AVX_INSTRUCTIONS with Raspberry Pi. It's an ARM processor and doesn't support that.

**Comment by RatchananPrasan** [comment]
Thank you, sir.
http://imgur.com/a/AwIzp
I will install again.

**Comment by ageitgey** [comment]
I haven't tried installing this on a Raspberry Pi yet. But here's some comments that might help:

http://www.pyimagesearch.com/2017/03/27/how-to-install-dlib/#comment-421292

They suggest increasing swap space in `/etc/dphys-swapfile` and using `raspi-config` to decrease the memory allocated to the GPU to leave more for the compiler.

**Comment by ageitgey** [comment]
I was able to install this on my Raspberry Pi 2. I [put the full instructions here](https://gist.github.com/ageitgey/1ac8dbe8572f3f533df6269dab35df65).

The main trick is to increase the swap file size before you compile dlib and then it works fine. Otherwise it will fail like you said.

I also added [a Raspberry Pi example](https://github.com/ageitgey/face_recognition/blob/master/examples/facerec_on_raspberry_pi.py) that shows how to capture images from the RPi camera and do face recognition on them.
