### ISSUE TITLE
Difference between knn and normal face recognition

### ISSUE THREAD

**Issue by postacik** [ageitgey/face_recognition#571]
The dlib dnn face recognition sample compares a found face in a picture with pre-found faces and decides that two faces are identical if the difference between the two is less than a certain threshold.

As far as I can understand, you do the same with the following command:

`$ face_recognition ./pictures_of_people_i_know/ ./unknown_pictures/`

That means, if I want to match a face to a database of faces, I have to compare the face with all the faces in the database until I find one with a diffence less than the desired threshold value.

Is the knn sample trying to make this process faster? If yes, how is it doing this?

**Comment by MaheshVishnu** [comment]
Yes, it does make it simpler. As KNN tries to find the k nearest neighbors it doesn't mean that it goes through all the data points to find those k nearest points. We can safely assume that the model has already constructed a graph denoting all training data points and now the model needs to search the region in which the new unseen point falls. This might appear to be a silly reasoning but it does matter because finding k nearest points really doesn't take O(n) time.

**Comment by postacik** [comment]
Thank you for your nice explanation.

But for the knn alternative, you have to re-construct your graph when you add additional faces to your database, is that right?

Assume you have a database of a few hundred employee faces which you use for monitoring the entrance gate of your company. You add 1 or 2 new faces every week to the database.

Which approach would be more suitable if you need live face recognition on video streaming from cameras?

**Comment by postacik** [comment]
I found my answers in these two issues:

https://github.com/ageitgey/face_recognition/issues/279
https://github.com/ageitgey/face_recognition/issues/238

Thanks...

**Comment by MaheshVishnu** [comment]
That's cool. But imho we need not reconstruct the whole graph in order to add or remove a small number of data points in the data set. We can add and remove data points to already existing graph with in O(k) time. However if the data set is highly volatile i.e a large part of data set whose size is comparable to that of the whole data set, changes frequently then it does take a considerable time to reconstruct the graph.

However even this should not take much time than normal face recognition which you mentioned. So, KNN is preferable to use i case of a low volatile data set and when you work with a highly volatile data set it is your choice as knn takes same time to train on changed data as that of training it for the first time,  but it does take less time to search your result as doesn't go through every data point to find the closest one.

Correct me if I'm wrong.

**Comment by postacik** [comment]
That's the conclusion I made, too. Thanks for your time. 👍
