### ISSUE TITLE
[Question] Affine transformation

### ISSUE THREAD

**Issue by AndreWicked** [ageitgey/face_recognition#574]
* face_recognition version: 1.2.2
* Python version: 3.5
* Operating System: Windows 10 x64

Hello! I'm studying this wonderful library, can not find where the affine transformation occurs, and is it produced before the extraction of the descriptors? I noticed that if I tilt my head in the side, then my face is recognized by another. Or do I need to do the affine transformation myself?

**Comment by ageitgey** [comment]
The affine transformation code is in dlib itself. It happens right before the face descriptors are extracted. It's a little tricky to find because it's kind of buried within helpers in the c++ code.

You can see the code here: https://github.com/davisking/dlib/blob/9848699fb98eba3f7d570c14379270c06262290c/dlib/image_transforms/interpolation.h#L2042-L2134

Which if you trace down, will lead you to this: https://github.com/davisking/dlib/blob/9848699fb98eba3f7d570c14379270c06262290c/dlib/image_transforms/interpolation.h#L1715-L1742

**Comment by AndreWicked** [comment]
Thank you very much for your reply, one less question. And thanks for the library.
