### ISSUE TITLE
GPU acceleration problem.

### ISSUE THREAD

**Issue by MikayelSmbatian** [ageitgey/face_recognition#588]
* face_recognition version: (1.2.2)
* Python version: 3.5.2
* Operating System: Linux Tegra Ubuntu 4.4.38-tegra

Hello, ageitgey. How are you? I hope you can help me.
I installed (using pip3) face_recognition library on my Jetson TX2 (with 256 CUDA cores). I was thinking that it would work much faster than my PC with Intel Core i3 processor and factory GPU. But no.

I manually built dlib and opencv and especially checking for CUDA and cuDNN usage. While building in outputs I noticed that Cuda and CuDNN was detected and build was successful. But again I got disappointed with speed.

I hope you can give me some good advices.

**Comment by ageitgey** [comment]
I don't know how fast a Jetson TX2 is. But I'm guessing it's not very fast since it's an embedded board. There's lots of factors that make your application faster or slower:

- Did you use the HOG face detection model or the CNN model?
- If CNN, how powerful is your GPU relative to something like a GT 1080 Ti
- How fast is the CPU
- How much RAM is available
- How large are your images? Smaller image sizes will be much faster
- Are you using upscaling in the face detector? If so, that will be slower.
- What exactly is your code doing? How is it pulling in images? Is it using all available CPU cores?
- Did you check `nvidia-smi` to see how much the GPU was being used during runtime?
- Is your application one where doing batch face detection might work? That would be a bit faster.
- If you are in a heavily speed-constrained environment, it might be better to write C++ code instead of using this Python library

...etc. You have to consider all those factors and adjust each to see how it effects output speed. It's not as simple as moving from a relatively slow computer to a relatively slow embedded board and that fixing performance problems.

**Comment by windforce7** [comment]
Performance of A Jetson TX2 in single-precision floating point is about 1.5 TFLOPS, which is relatively small compared to common PC GPUs such as GTX970(4.2TFLOPS). And its memory bandwidth is less than 1/3 of GTX970. (see discussions on CUDA forum https://devtalk.nvidia.com/default/topic/1024825/jetson-tx2-performance/).
Doing a face_encodings on an 1080p image takes about 1.5-2 secs with 970. So your device could use 3x time to complete the same task, not to mention you may have set a different upsample parameter which would greatly increase task scale and memory consumption.

**Comment by MikayelSmbatian** [comment]
Thank you all.
