### ISSUE TITLE
Data protection question

### ISSUE THREAD

**Issue by jonwitts** [ageitgey/face_recognition#64]
I am really interested in using your library in the school I teach in with our Raspberry Pi computers. However most other facial recognition solutions I have looked at upload the picture to a server for analysis. Due to UK Data Protection laws this pretty much stops us using these in schools.

Is all of the processing carried out locally with your library or do the pictures get uploaded anywhere?

**Comment by ageitgey** [comment]
Cool!

Don't worry, this does all processing on the device itself. It never connects to any other service nor transfers any data over the internet.

But of course since all the processing happens on the device and Raspberry Pis are pretty slow at running deep learning models, the performance might be worse than using a cloud-based solution. You can see in the RPi example code that I scale the camera images down to 320x240 pixels to make it run at a usable speed.
