### ISSUE TITLE
It is ran slowly at RASPBERRY PI, and I want to retrain the face recognition model with more face images  and get more API for development

### ISSUE THREAD

**Issue by knaffe** [ageitgey/face_recognition#72]
* face_recognition version: the newest one(2017.4.30) aff06e96
* Python version: 3.4
* Operating System: ubuntu14.04 and Raspbian Jessie

### Description
Thank you for your great job!!
I ran the  sample "facerec_from_webcam_faster.py" in ubuntu and Raspbian. it worded well in Ubuntu but not in Raspbian. In Raspbian, the recognition or the detection is very slow. How can I improve the speed?

### What I Did
 I want to retrain the face recognition model. I just read the Article name "Machine Learning is Fun! Part 4: Modern Face Recognition with Deep Learning" which talk about the inside of how recognition worked. Should I use open face library to retrain my model if I want to do more things on face recognition? Because I want to finish a robust and real-time system in PI. 
Another question, Do you finish your face_recognition Library based on Open Face? Have you do something about optimization?
Could you open more API of the Great project? Sometimes I want to use your lib to do more things conveniently. 
Thank you for your GREAT JOB!!!

**Comment by ageitgey** [comment]
### Raspberry Pi speed

The face_encodings() method runs a feed-forward pass on a deep neural network, which is basically all matrix multiplication. 

Modern Intel CPUs have support for SSE4/AVX SIMD instructions which parallelize that math in the CPU for a big speed boost. The RPi's ARM cpu doesn't support SSE instructions. ARM has it's own SIMD feature called NEON but unfortunately dlib doesn't currently support NEON so it doesn't take advantage of SIMD to speed things up. That's why it's so slow on RPi.

Someone made an unofficial dlib patch that uses NEON instructions on ARM, but it's totally unsupported and probably doesn't work for face recognition unless someone did some more work on it: https://github.com/fastfastball/dlib_for_arm

There's also an open issue on dlib asking for ARM NEON support, but it hasn't been implemented yet: https://github.com/davisking/dlib/issues/276

So unless you are able to contribute to dlib in this area, unfortunately the best short-term answer is to just reduce the resolution of the image as low as you can to keep the face recognition times reasonable on RPi. Hopefully it will get better soon!

### Re-training, etc

This library uses [dlib](http://dlib.net/).  You can use dlib directly if you need more flexibility.  You can see more info about re-training here on the dlib blog: http://blog.dlib.net/2017/02/high-quality-face-recognition-with-deep.html

**Comment by knaffe** [comment]
Thank you for your great answer!!!
From your words, your face recognition method (deep learning model, 128 dims features)is based on Dlib (ResNet)? Do you think the most expensive part of cost time is face detection or the extra facial feature? One of the optimization of speed is to narrow the area (ROI) to detect face and recognition I think.
Moreover,  I want to try Caffe2 and train a simple CNN for face recognition. Do you have some advice of face recognition methods run on Raspberry Pi.

**Comment by bakercp** [comment]
neon SIMD is now implemented in dlib and tested on Raspberry Pi (see some results [here](https://github.com/davisking/dlib/issues/557)).

**Comment by knaffe** [comment]
How to use Neno in python interfaces? I have seen your posts from your link, but it is used in c++.

**Comment by jyurek** [comment]
You run `python setup.py --compiler-flags "-mfpu=neon"`: https://github.com/davisking/dlib/issues/615

My problem now is that this still isn't fast enough and I'm unsure where the bottleneck is. Facial detection on my Pi3b is (with the above flag) 1.5s for an empty frame, 2.8s for one face, and 4.5s for 2 faces. This is not nearly fast enough for real time and I don't know how to proceed.

**Comment by openedhardware** [comment]
Hi, @bakercp 
I saw that you had used `-O3 -mfpu=neon -fprofile-use` instead of `-mfpu=neon` to get 444ms of duration while the first option was 1267ms.
https://github.com/davisking/dlib/issues/557#issuecomment-298230416

Is this OK to use this?

**Comment by hbthegreat** [comment]
Hi @jyurek I was about to go down the same route with a project I am attempting. Just confirming is that 2.8s for one face just detection or is that including recognition as well? If so that is far too slow and I may have to skip out on the pi3b and use something a bit more beefy.

**Comment by jyurek** [comment]
I don't have times on detection without recognition, and I don't have my Pi in front of me. I think it's safe to say it's somewhere north of 2s though, given that an empty frame is 1.5s. I can check in a few days though.

**Comment by ageitgey** [comment]
BTW, neon is now supported in dlib. So compile dlib's python model with "-mfpu=neon" to get a big speed-up.
