### ISSUE TITLE
Using only one face detected from video feed

### ISSUE THREAD

**Issue by mohahadi** [ageitgey/face_recognition#76]
I don't want to get face_encodings from all faces detected. Is there way to choose one 'best' face from all those detected and get it's encodings?

**Comment by sluongng** [comment]
Im not certain on this but in @ageitgey 's original article he mentioned that you are supposed to run a simple SVM on the encodings.
Check out the article here: https://medium.com/@ageitgey/machine-learning-is-fun-part-4-modern-face-recognition-with-deep-learning-c3cffc121d78

**Comment by ageitgey** [comment]
What do you mean by "best" face? The biggest face in the picture? 

If so, you could just check the size of each face bounding box returned by `.face_locations()` and then pass only the ones you want to [`.face_encodings(img, face_locations=[just-the-biggest-face])`](https://face-recognition.readthedocs.io/en/latest/face_recognition.html#face_recognition.api.face_encodings).

**Comment by sluongng** [comment]
@ageitgey I believe the question was something like "Why was it that your face encoding is only using 1 image instead of multiple"? What if you want to use multiple images to help improve face identification?

Am I right to assume that you will have to use SVM in combination with your face_encodings results if we want to use multiple images of 1 person?

**Comment by ageitgey** [comment]
Sure, you can use an SVM classifier if you want to use multiple face encodings of each single person.

**Comment by sluongng** [comment]
@ageitgey have you consider provide support for a classifier, similar to OpenFace, which support multiple faces for each person, multiple-person classification (SVM) included. I think that would be very much helpful here

**Comment by ageitgey** [comment]
I don't really want to complicate the API of the library with classifier functions since they often aren't needed (and also because how you use a classifier will depend on what exactly you want to do).  But maybe when I have some spare time I can add a new example program that shows how to use a basic classifier with scikit-learn.

**Comment by mohahadi** [comment]
I was referring to scenarios where in a video/picture will have more than 1 face detected and you only want to perform the facial recognition on one face out of the many detected).

**Comment by sluongng** [comment]
use this
```python
face_locations = face_recognition.face_locations(small_frame)
face_encodings = face_recognition.face_encodings(small_frame, face_locations)
```

and then `face_encodings[0]` for the first face you find

You can ofc do further conditioning based on the location of the face.

**Comment by mohahadi** [comment]
that's exactly what I need, thanks!
