### ISSUE TITLE
Conda support?

### ISSUE THREAD

**Issue by sluongng** [ageitgey/face_recognition#81]
* face_recognition version: latest
* Python version: 3.6
* Operating System: Windows 10 64bits

### Description

Hi I am trying to install this on my conda python 3.6 environment.

I managed to install dlib 19.4.0 via using conda-forge channel and I can import it just fine.

![image](https://cloud.githubusercontent.com/assets/26684313/26084328/7fb7e484-3a05-11e7-8852-fc18d5aa5f4c.png)

However I cannot install face_recognition (using pip) because it will attempt to install dlib again and fail.

I dont think you support installing via conda either right?

### What I Did

```
conda create -n py36 python=3.6

activate py36

conda install -c conda-forge dlib=19.4

pip install face_recognition
```

here the installation will fail to detect that dlib has already been installed and attempt to re-install it and fail

**Comment by ageitgey** [comment]
You're correct that Conda isn't currently supported. But having Conda support would be really cool - especially on Windows where this library is currently nearly impossible to install! 

Unfortunately I don't know much about how Conda works or what would be required to make this work with `conda install`. If anyone knows, let me know! Otherwise I'll take a look when I have a little free time.

**Comment by fhboswell** [comment]
If you use docker (there is an example provided) you can use a windows machine to run it virtually.
I recommend it.

@ageitgey awesome library btw.

**Comment by sluongng** [comment]
The docker image, iirc, use 3.5 while I am looking for a 3.6 option.

And you are absolutely correct that libraries has been next to impossible to deal with on window. I am following @ageitgey original tutorial using OpenFace and dlib with plan to move on to this library later. The manual compile process of dlib and Boost has been such a nightmare and Conda helped so much.

Probably gona give the docker thing a try, downloaded VMWare last night too. But its shitty that I have to run things on a virtual environment.

**Comment by fhboswell** [comment]
I had to learn Docker in order to run this library as well. Using Docker was significantly more straight forward than I thought it would be. IMO Docker is far less overhead than using VMWare with the GUI and everything.

I followed this guide. https://docs.docker.com/get-started/. 
During step 2 instead of making a new directory and dockerfile just CD into your local clone of this repository. 

If you need 3.6 you can just change the Dockerfile it is pretty straight forward.

**Comment by sluongng** [comment]
@fhboswell do you mind making a quick markdown for docker installation for this particular library? Just a functional brief GIST maybe and then we could pull request on that and include it to the main readme.md

**Comment by fhboswell** [comment]
Yes I will do that!

**Comment by sluongng** [comment]
@fhboswell I would be happy with just a guide showing how stuff in `\examples` run with docker

**Comment by ageitgey** [comment]
Almost all the issues people have with installation are with installing dlib. There's only so much I can do since I don't maintain dlib itself. I've provided installation dlib instructions for OSX and Linux and a pre-made virtual machine for other users. But beyond that, I'm not sure what I can do. I don't use Windows myself.

Hopefully the awesome folks who package dlib for anaconda will get that all working and then I can just direct Windows users to install with Anaconda.

**Comment by sluongng** [comment]
as mentioned over #89 , conda solved so much problem with installation for me.

I strongly suggest people to use it over normal lib, especially with dlib and opencv getting involved.

I will be closing this issue thread for now but I do hope @ageitgey will consider conda distribution in the future ✌️

**Comment by phizaz** [comment]
I did as you said, conda-forge's dlib, pip install dlib, pip install face_recognition. I didn't fail. It worked! 

I don't know how could pip possibly locate the wheel file:

```
Collecting dlib                                                                                                       
  Downloading dlib-19.7.0-cp36-cp36m-win_amd64.whl (2.2MB)                                                            
Installing collected packages: dlib                                                                                   
Successfully installed dlib-19.7.0         
```

**Comment by mhmtozkan** [comment]
I am using Windows 10,python 3.5 and pycharm editor. I installed dlib from Anaconda cloud successfully. But when i try to work sample code for face recognition via webcam, i am getting error "No module named face_recognition" . When i try to import dlib, there is no problem. Is there anyone help me?

**Comment by damvantai** [comment]
> I am using Windows 10,python 3.5 and pycharm editor. I installed dlib from Anaconda cloud successfully. But when i try to work sample code for face recognition via webcam, i am getting error "No module named face_recognition" . When i try to import dlib, there is no problem. Is there anyone help me?

you need pip instal face_recognition for conda

**Comment by a-kanaan** [comment]
this should help
https://stackoverflow.com/a/52803626/2696230

**Comment by a-kanaan** [comment]
check cmake
https://stackoverflow.com/a/52803626/2696230
