### ISSUE TITLE
Effective usage of SVM for unknown faces and small datasets

### ISSUE THREAD

**Issue by pliablepixels** [ageitgey/face_recognition#979]
* face_recognition version: 1.2.3
* Python version: 3.6
* Operating System: OSX

### Description

I've been experimenting with using SVMs for working with multiple faces per person, based on the example for SVM [here](https://github.com/ageitgey/face_recognition/blob/master/examples/face_recognition_svm.py).

Here are the challenges I am facing:

- using `clf.predict` ([ref](https://github.com/ageitgey/face_recognition/blob/master/examples/face_recognition_svm.py#L79))  _always_ matches to at least one known category. How do we go about setting a threshold of some sorts to _not_ match a category? We need this to say "I don't recognize that face" 

- Unfortunately, enabling `probability=True` while instantiating the `SVC` and then using `predict_proba` doesn't work at all for small datasets. All probabilities are almost evenly split between categories even when you directly supply the same image you used for training. The sklearn [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html) also corroborates this -> 'Also, it will produce meaningless results on very small datasets'
- knn works well, maybe SVM is not suited for this case?

Thanks.

**Comment by iyedg** [comment]
I have used a KNN for a similar task to exploit the fact I can use the fact I can get a distance from the new observation. For instance if I have a 3 NN model, I use the [kneighbors ](https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html#sklearn.neighbors.KNeighborsClassifier.kneighbors)function on the trained model to get an array of distances, which I then average and compare to a certain threshold, that is if the average distance of the new observation is lower than my threshold, I would return the model's prediction, otherwise I would return that the face has not been recognized.

If you insist on using SVM, you should look into one-class SVM, which are generally used for outlier-detection, but could be used in your case to detect if a new observation is an 'outlier' to your training set.

**Comment by pliablepixels** [comment]
Thank you. Yes I’ve abandoned SVMs and gone with KNNs. I did not realize this was still open.
